### ISSUE TITLE
Manifest file documentation

### ISSUE THREAD

**Issue by timvdalen** [Happening/Example#2]
This might not be the place for it, but I don't know where else to create it.

I couldn't find any documentation on the `manifest` file.
Most options are guessable from the existing plugins, but can we get an overview of valid icons?

**Comment by EmielM** [comment]
README.md is updated and now contains a link to all available icons.

https://github.com/Happening/Example/blob/master/README.md
https://happening.im/static/plugicons.html

**Comment by timvdalen** [comment]
Thanks! /cc @StefvanSchuylenburg
