### ISSUE TITLE
Deploy script does not work on Windows

### ISSUE THREAD

**Issue by LeslieAerts** [Happening/Example#5]
Any proper way to deploy stuff on Windows? Currently using POSTman to deploy on the happening.im URL, but it's a bit messy.

**Comment by lesteenman** [comment]
Do you have Git for Windows installed? Its shell should be able to run the deploy script.

**Comment by LeslieAerts** [comment]
Using the script results in "This script requires the zip command in your path". Removing the check and the zip command from the script makes it work, but it doesn't work by default.

**Comment by narimantos** [comment]
i have the same problem. Going to remove the check and try

edit: Still not working

**Comment by Henridv** [comment]
You can use [Cygwin](https://www.cygwin.com/). During installation select a.o. git and zip

**Comment by EmielM** [comment]
I think you can download a suitable zip.exe from http://gnuwin32.sourceforge.net/packages/zip.htm. We should add this to the README.

**Comment by JobSavelsberg** [comment]
You can also use the terminal and/or coding environment of this application (virtual cloud machine)
Everything should work straight away, no installs or setups needed.
https://koding.com/
