### ISSUE TITLE
When obtaining list of user ids with Plugin.userIds(), users left from group show up as well

### ISSUE THREAD

**Issue by LeslieAerts** [Happening/Example#6]
This is giving issues when looping over players and giving them a choice. Is there an alternative or a way to check if a user is valid? I could personally do with a bit more Plugin documentation as well.

**Comment by EmielM** [comment]
The server-side `Plugin.userIds()` call should not include members that have left. Could you supply the id of a group and the unexpected output of the call?

**Comment by LeslieAerts** [comment]
Simple but probably bad snippet where it occurs:

```
id = Db.shared.get 'userId' 
id += 1     
if id > Plugin.userIds().length
    #Back to first id (1)
    id = 1

log "Next player should be: " + Plugin.userName(id)
Db.shared.set 'userId', id
```

The username will return the empty player's name

**Comment by EmielM** [comment]
User IDs are not guaranteed to be incremental `1, 2, 3, ...` (in fact, for some older Happening groups, user IDs are completely random). If you want to incrementally loop over IDs I'd use the following:

```
userIds = Plugin.userIds()
id = Db.shared.get 'userId'
idx = userIds.indexOf(id)
nextId = userIds[if idx? then (idx+1)%userIds.length else 0]
# nextId can be undefined if all people left the group
```

**Comment by LeslieAerts** [comment]
Thanks, that works great! I was printing userIds and in our case, it was an incremental number.
