### ISSUE TITLE
Global variable 'data' cannot be used in sandboxed code

### ISSUE THREAD

**Issue by Pindagus** [Happening/Example#7]
When I try to deploy the example, the following error occurs.
![screenshot_4](https://cloud.githubusercontent.com/assets/2330211/7505567/4234e556-f454-11e4-9b74-d3cac30e1739.png)

**Comment by EmielM** [comment]
Oops, my bad! It is now fixed - please do a clean checkout of the Example repository because history has been rewritten to keep the example in a single patch.. :)
