### ISSUE TITLE
Syntax question

### ISSUE THREAD

**Issue by Jelmertje** [Happening/Example#8]
Heya,

I noticed that when declaring and calling functions, that instead of the conventional '= ->' sometimes a different syntax seems to be used namely '= !->' with an exclamation mark.

It seems to happen primarily when a function is called from another library e.g:
Dom.div !->

or sometimes when a function is declared in the server.coffee script e.g:
exports.onPhoto = (info) !->

Why is this? The javascript this compiles into also shows the exclamation mark so it makes me suspect it does something. Is it just for readability? Does it impact the return value?
How should i pay attention to this? Can I just forget about the '!' or do I have to use them?

**Comment by lesteenman** [comment]
Don't pin me on this, but I believe this is custom syntax for Happening. 

By default, Coffeescript returns the last evaluated statement in a function. By writing `!->` instead of `->`, no value is implicitly returned. 

**Coffeescript Function Implicit Return**

```
test = ->
    5 + 5
```

Compiles to:

```
var test;
test = function() {
    return 5 + 5;
};
```

**Coffeescript Function Without Implicit Return**

```
test = !->
    5 + 5
```

Compiles to:

```
var test;
test = function() {
    5 + 5;
};    
```

**Comment by Jelmertje** [comment]
Yeah, that's was my initial thought as well, but I figured I could test this out by compiling both codes on coffeescript.org and it turns out it compiles as follows:

```
test = ->
    5 + 5

test = !->
    5 + 5
```

become respectively:

```
var test;

test = function() {
  return 5 + 5;
};

test = !function() {
  return 5 + 5;
};
```

EDIT:
 I just tried what would happen if I put in:

```
test = !->
  return 5+5
alert test
```

It turns out it returns false.
I guess I now know enough to not worry about it anymore :)
