### ISSUE TITLE
"Global variable 'Document' cannot be used in sandboxed code"

### ISSUE THREAD

**Issue by tcelis** [Happening/Example#9]
![image](https://cloud.githubusercontent.com/assets/17416042/13233830/e6f94dce-d9b5-11e5-9624-af24244946ad.png)

I'm trying to deploy the example but I get this error. Am I missing something?

**Comment by EmielM** [comment]
It seems you're not using the latest version from this repository (latest `api` in `manifest` is 3), `Document` is no-where to be found in the current sources. Please update the example repository.
